// #include<iostream>

// using namespace std;



// class MyException: public std:: exception
// {
//     private:
//         string m_error;
//     public:
//         MyExpection(string error) : m_error(error){}


//     consr char *what()



// int main()
// {
//     try {
//         int i;
//         cout << "Enter a number; ";
//         sin >> i;


//         if(i > 0){
//             throw MYyException("Error message goes here!");
//         }


//         if

//     }
// }



















































